language: node_js
dist: trusty
sudo: false
services:
    - mongodb
before_install:
    - npm i -g npm@6.4.0
before_script:
    - sleep 15
cache:
    directories:
        - "node_modules"

branches:
    only:
        - master
        - dev

notifications:
    slack: hackboard8:35nI0TJmTGbi6uQ3OfBSSoh5
